---
apiVersion: v2
name: dagster
version: 1.9.6
kubeVersion: ">= 1.18.0-0"
description: The data orchestration platform built for productivity.
type: application
keywords:
  - analytics
  - data-orchestrator
  - data-pipelines
  - etl
  - workflow
sources:
  - https://github.com/dagster-io/dagster/tree/master/helm/dagster
dependencies:
  - name: dagster-user-deployments
    version: 1.9.6
    condition: dagster-user-deployments.enableSubchart
  - name: postgresql
    version: 8.1.0
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: postgresql.enabled
  - name: rabbitmq
    version: 6.16.3
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: rabbitmq.enabled
  - name: redis
    version: 12.7.4
    repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
    condition: redis.internal
maintainers:
  - name: Dagster Labs
    email: support@dagsterlabs.com
    url: https://dagster.io/about
icon: https://dagster.io/images/brand/logos/dagster-primary-mark.png
appVersion: dev
